"""Initial migration

Revision ID: 6742aa9f0232
Revises: 
Create Date: 2026-07-20 10:34:24.547340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6742aa9f0232'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_active_sessions_refresh_token_hash'), table_name='active_sessions')
    op.drop_index(op.f('idx_active_sessions_user_id'), table_name='active_sessions')
    op.create_index(op.f('ix_active_sessions_refresh_token_hash'), 'active_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_active_sessions_user_id'), 'active_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('idx_attendance_user_time'), table_name='attendance_events')
    op.drop_index(op.f('idx_audit_logs_action_time'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_actor_time'), table_name='audit_logs')
    op.alter_column('doctors', 'commission_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('idx_expenses_date_cat'), table_name='expenses')
    op.drop_index(op.f('idx_expenses_expense_date'), table_name='expenses')
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_recorded_by'), 'expenses', ['recorded_by'], unique=False)
    op.alter_column('face_embeddings', 'embedding',
               existing_type=sa.TEXT(),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=128),
               existing_nullable=False)
    op.drop_index(op.f('idx_face_embeddings_user_id'), table_name='face_embeddings')
    op.create_index(op.f('ix_face_embeddings_user_id'), 'face_embeddings', ['user_id'], unique=False)
    op.drop_index(op.f('idx_login_history_email_attempted'), table_name='login_history')
    op.drop_index(op.f('idx_login_history_email_time'), table_name='login_history')
    op.drop_index(op.f('idx_login_history_user_id'), table_name='login_history')
    op.create_index(op.f('ix_login_history_email_attempted'), 'login_history', ['email_attempted'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.drop_index(op.f('idx_patient_test_results_patient_id'), table_name='patient_test_results')
    op.drop_index(op.f('idx_patient_test_results_test_id'), table_name='patient_test_results')
    op.drop_index(op.f('idx_patient_tests_patient_id'), table_name='patient_tests')
    op.drop_index(op.f('idx_patient_tests_test_id'), table_name='patient_tests')
    op.create_index(op.f('ix_patient_tests_patient_id'), 'patient_tests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_tests_test_id'), 'patient_tests', ['test_id'], unique=False)
    op.drop_index(op.f('idx_patient_code_prefix'), table_name='patients', postgresql_ops={'patient_code': 'varchar_pattern_ops'}, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_patients_active_collector'), table_name='patients', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_patients_active_created'), table_name='patients', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_patients_active_doctor'), table_name='patients', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_patients_active_mobile'), table_name='patients', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_patients_active_status'), table_name='patients', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_patients_amount_due'), table_name='patients', postgresql_where='((deleted_at IS NULL) AND (amount_paid < (total_amount - discount_amount)))')
    op.drop_index(op.f('idx_patients_collected_by'), table_name='patients')
    op.drop_index(op.f('idx_patients_doctor_id'), table_name='patients')
    op.drop_index(op.f('idx_patients_mobile_prefix'), table_name='patients', postgresql_ops={'mobile': 'varchar_pattern_ops'}, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_patients_name_trgm'), table_name='patients', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_patients_payment_split'), table_name='patients', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_patients_collected_by'), 'patients', ['collected_by'], unique=False)
    op.create_index(op.f('ix_patients_doctor_id'), 'patients', ['doctor_id'], unique=False)
    op.drop_index(op.f('idx_reports_patient_id'), table_name='reports')
    op.drop_index(op.f('idx_reports_patient_version'), table_name='reports')
    op.drop_index(op.f('idx_reports_uploaded_by'), table_name='reports')
    op.drop_index(op.f('idx_reports_verification_hash'), table_name='reports')
    op.create_index(op.f('ix_reports_patient_id'), 'reports', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reports_uploaded_by'), 'reports', ['uploaded_by'], unique=False)
    op.drop_index(op.f('idx_test_parameters_test_id'), table_name='test_parameters')
    op.drop_index(op.f('idx_tests_name_lower'), table_name='tests')
    op.drop_index(op.f('idx_tests_name_trgm'), table_name='tests', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_users_staff_active'), table_name='users', postgresql_where="(role = 'staff'::role_enum)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_staff_active'), 'users', [sa.literal_column('created_at DESC')], unique=False, postgresql_where="(role = 'staff'::role_enum)")
    op.create_index(op.f('idx_tests_name_trgm'), 'tests', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_tests_name_lower'), 'tests', [sa.literal_column('lower(name::text)')], unique=False)
    op.create_index(op.f('idx_test_parameters_test_id'), 'test_parameters', ['test_id', 'display_order'], unique=False)
    op.drop_index(op.f('ix_reports_uploaded_by'), table_name='reports')
    op.drop_index(op.f('ix_reports_patient_id'), table_name='reports')
    op.create_index(op.f('idx_reports_verification_hash'), 'reports', ['verification_hash'], unique=False)
    op.create_index(op.f('idx_reports_uploaded_by'), 'reports', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_reports_patient_version'), 'reports', ['patient_id', sa.literal_column('version DESC')], unique=False)
    op.create_index(op.f('idx_reports_patient_id'), 'reports', ['patient_id'], unique=False)
    op.drop_index(op.f('ix_patients_doctor_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_collected_by'), table_name='patients')
    op.create_index(op.f('idx_patients_payment_split'), 'patients', ['payment_mode', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_patients_name_trgm'), 'patients', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_patients_mobile_prefix'), 'patients', ['mobile'], unique=False, postgresql_ops={'mobile': 'varchar_pattern_ops'}, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_patients_doctor_id'), 'patients', ['doctor_id'], unique=False)
    op.create_index(op.f('idx_patients_collected_by'), 'patients', ['collected_by'], unique=False)
    op.create_index(op.f('idx_patients_amount_due'), 'patients', [sa.literal_column('created_at DESC')], unique=False, postgresql_where='((deleted_at IS NULL) AND (amount_paid < (total_amount - discount_amount)))')
    op.create_index(op.f('idx_patients_active_status'), 'patients', ['status', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_patients_active_mobile'), 'patients', ['mobile'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_patients_active_doctor'), 'patients', ['doctor_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_patients_active_created'), 'patients', [sa.literal_column('created_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_patients_active_collector'), 'patients', ['collected_by', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_patient_code_prefix'), 'patients', ['patient_code'], unique=False, postgresql_ops={'patient_code': 'varchar_pattern_ops'}, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_patient_tests_test_id'), table_name='patient_tests')
    op.drop_index(op.f('ix_patient_tests_patient_id'), table_name='patient_tests')
    op.create_index(op.f('idx_patient_tests_test_id'), 'patient_tests', ['test_id'], unique=False)
    op.create_index(op.f('idx_patient_tests_patient_id'), 'patient_tests', ['patient_id'], unique=False)
    op.create_index(op.f('idx_patient_test_results_test_id'), 'patient_test_results', ['test_id'], unique=False)
    op.create_index(op.f('idx_patient_test_results_patient_id'), 'patient_test_results', ['patient_id'], unique=False)
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_email_attempted'), table_name='login_history')
    op.create_index(op.f('idx_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_login_history_email_time'), 'login_history', ['email_attempted', sa.literal_column('attempted_at DESC')], unique=False)
    op.create_index(op.f('idx_login_history_email_attempted'), 'login_history', ['email_attempted'], unique=False)
    op.drop_index(op.f('ix_face_embeddings_user_id'), table_name='face_embeddings')
    op.create_index(op.f('idx_face_embeddings_user_id'), 'face_embeddings', ['user_id'], unique=False)
    op.alter_column('face_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_expenses_recorded_by'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.create_index(op.f('idx_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('idx_expenses_date_cat'), 'expenses', [sa.literal_column('expense_date DESC'), 'category'], unique=False)
    op.alter_column('doctors', 'commission_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.create_index(op.f('idx_audit_logs_actor_time'), 'audit_logs', ['actor_user_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_logs_action_time'), 'audit_logs', ['action', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index(op.f('idx_attendance_user_time'), 'attendance_events', ['user_id', sa.literal_column('event_time DESC')], unique=False)
    op.drop_index(op.f('ix_active_sessions_user_id'), table_name='active_sessions')
    op.drop_index(op.f('ix_active_sessions_refresh_token_hash'), table_name='active_sessions')
    op.create_index(op.f('idx_active_sessions_user_id'), 'active_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_active_sessions_refresh_token_hash'), 'active_sessions', ['refresh_token_hash'], unique=False)
    # ### end Alembic commands ###
